theme: jekyll-theme-hacker
future: true
timezone: US/Pacific

title: AndrewTFesta
description: Unfortunate stopping place for people to peer into who I am.

google_analytics: G-TC75PLNSM8
repository: AndrewTFesta/andrewtfesta
